# Enable C++ support
language: cpp
# Compiler selection
compiler:
  - g++
  - clang

os:
    - linux
    # - osx

# Build steps
script:
 - make
 - ./build/main master
 #- mkdir build && cd build
 # - cmake -Dtest=ON .. && make -j8
after_success:
#- bash <(curl -s https://codecov.io/bash)
